### ISSUE TITLE
Any chance to rename "StatusCodes" to "HTTP"?

### ISSUE THREAD

**Issue by hopeseekr** [koriym/Koriym.HttpConstants#4]
Hi, 

Is there any chance on renaming "StatusCodes" to "HTTP"?

I'm currently doing:

```php
use Koriym\HttpConstants\StatusCode as HTTP;
```

everywhere, but it is cumbersome.

Tell me: What is more readable:

```php
        if ($this->api->getLastStatusCode() !== StatusCodes::NO_CONTENT) {
```
or
```php
        if ($this->api->getLastStatusCode() !== HTTP::NO_CONTENT) {
```

`StatusCodes` gives no clue that it's related to HTTP status codes.

**Comment by koriym** [comment]
Hi @hopeseekr 

Asked a few people about this and get a similar response like this. https://twitter.com/Ocramius/status/1144955393627631617

But I also found used a lot in GH.
https://github.com/search?q=%22HTTP%3A%3ANO_CONTENT%22&type=Code
 
What about if I remove `final` keyword then you can have your own alias in your class?

**Comment by cgray** [comment]
I would like to add that StatusCodes::NO_CONTENT doesn't advertise the fact that is HTTP, HTTP::NO_CONTENT doesn't indicate that the constant represents a status code.

**Comment by koriym** [comment]
Yes, but if you look only at the last word.
Fully qualified names is `<vendor_name>\HttpConstants\StatusCode`.

**Comment by koriym** [comment]
There is no reaction after 10 days, so it closes.
