### ISSUE TITLE
RequestHeader misses Content-Type

### ISSUE THREAD

**Issue by arecdudek** [koriym/Koriym.HttpConstants#8]
Hi @koriym,
After last update again RequestHeader misses Content-Type:
https://github.com/koriym/Koriym.HttpConstants/pull/7/files#diff-e6f0b6f649d8b14ae069be889828d00fc724a707c90414e02801c44ed5e2b8eeL24

Could you restore it?

**Comment by koriym** [comment]
Relased. https://github.com/koriym/Koriym.HttpConstants/releases/tag/1.2.1
Thank you for the reporting!
